import { ResumeData, ResumeStyle } from '../types/resume';

// Helper to escape special LaTeX characters to prevent compilation errors
export function escapeLatex(text: string): string {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/</g, '\\textless{}')
    .replace(/>/g, '\\textgreater{}');
}

export function generateResumeLatex(data: ResumeData, style: ResumeStyle): string {
  const info = data.personalInfo;
  
  // Format primary hex color for LaTeX
  const primaryHex = style.colorPalette.primary.replace('#', '').toUpperCase();
  const secondaryHex = style.colorPalette.secondary.replace('#', '').toUpperCase();
  const textHex = style.colorPalette.text.replace('#', '').toUpperCase();
  
  // Choose LaTeX font based on settings
  let fontPreamble = '';
  if (style.fontFamily === 'serif') {
    fontPreamble = '\\usepackage{charter} % Serif font';
  } else if (style.fontFamily === 'mono') {
    fontPreamble = '\\usepackage{inconsolata} % Monospace font';
  } else {
    fontPreamble = '\\usepackage{helvet} \\renewcommand{\\familydefault}{\\sfdefault} % Sans-serif';
  }

  let latex = `%-------------------------
% Resume generated by OpenResume AI
% Private, local, and ATS-friendly CV builder
%-------------------------

\\documentclass[letterpaper,${style.fontSizeBase}pt]{article}

\\usepackage[empty]{fullpage}
\\usepackage{geometry}
\\usepackage{titlesec}
\\usepackage{xcolor}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage{tabularx}
${fontPreamble}

% Set Page Margins
\\geometry{
  letterpaper,
  left=${(style.marginSize / 72).toFixed(2)}in,
  right=${(style.marginSize / 72).toFixed(2)}in,
  top=${(style.marginSize / 72).toFixed(2)}in,
  bottom=${(style.marginSize / 72).toFixed(2)}in
}

% Define Colors
\\definecolor{primaryColor}{HTML}{${primaryHex}}
\\definecolor{secondaryColor}{HTML}{${secondaryHex}}
\\definecolor{textColor}{HTML}{${textHex}}

% Page Layout Adjustments
\\pagestyle{fancy}
\\fancyhf{} 
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}
\\urlstyle{same}

% Section Header Formatting
\\titleformat{\\section}{
  \\vspace{-10pt}\\scshape\\raggedright\\large\\bfseries\\color{primaryColor}
}{}{0em}{}[\\color{primaryColor}\\titlerule \\vspace{-5pt}]

% Custom list environment for bullet points
\\newlist{resumeItemize}{itemize}{1}
\\setlist[resumeItemize]{
  label=\\textbullet,
  leftmargin=0.15in,
  rightmargin=0in,
  topsep=2pt,
  itemsep=2pt,
  parsep=0pt,
  partopsep=0pt
}

\\begin{document}
\\color{textColor}

%====================
% CONTACT HEADER
%====================
\\begin{center}
  {\\Huge \\bfseries \\color{primaryColor} ${escapeLatex(info.fullName)}} \\\\[4pt]
  {\\large \\itshape \\color{secondaryColor} ${escapeLatex(info.title)}} \\\\[6pt]
  \\small
  ${info.email ? `\\href{mailto:${info.email}}{${escapeLatex(info.email)}}` : ''}
  ${info.phone ? ` \\textbullet{} ${escapeLatex(info.phone)}` : ''}
  ${info.location ? ` \\textbullet{} ${escapeLatex(info.location)}` : ''} \\\\[2pt]
  ${info.website ? `\\href{${info.website}}{${escapeLatex(info.website.replace('https://', '').replace('http://', ''))}}` : ''}
  ${info.linkedin ? ` \\textbullet{} \\href{${info.linkedin}}{linkedin.com/in/${escapeLatex(info.linkedin.split('/in/')[1] || '')}}` : ''}
  ${info.github ? ` \\textbullet{} \\href{${info.github}}{github.com/${escapeLatex(info.github.split('.com/')[1] || '')}}` : ''}
\\end{center}

`;

  // 1. Profile Summary Section
  if (info.summary) {
    latex += `%====================
% PROFILE SUMMARY
%====================
\\section{Profile Summary}
${escapeLatex(info.summary)}

\\vspace{10pt}
`;
  }

  // 2. Experience Section
  if (data.workExperience.length > 0) {
    latex += `%====================
% WORK EXPERIENCE
%====================
\\section{Professional Experience}
`;

    for (const job of data.workExperience) {
      const dates = `${job.startDate} -- ${job.current ? 'Present' : job.endDate}`;
      latex += `\\noindent
\\textbf{\\color{primaryColor}${escapeLatex(job.company)}} \\hfill \\small ${escapeLatex(job.location)} \\\\
\\textit{${escapeLatex(job.position)}} \\hfill \\small \\textit{${escapeLatex(dates)}}
\\begin{resumeItemize}
`;
      for (const bullet of job.description) {
        latex += `  \\item ${escapeLatex(bullet)}\n`;
      }
      latex += `\\end{resumeItemize}
\\vspace{6pt}
`;
    }
    latex += `\\vspace{4pt}\n`;
  }

  // 3. Projects Section
  if (data.projects.length > 0) {
    latex += `%====================
% PROJECTS
%====================
\\section{Key Projects}
`;

    for (const proj of data.projects) {
      latex += `\\noindent
\\textbf{${escapeLatex(proj.name)}} \\hfill ${proj.link ? `\\href{${proj.link}}{\\small \\color{secondaryColor} ${escapeLatex(proj.link.replace('https://', '').replace('http://', ''))}}` : ''} \\\\
\\textit{${escapeLatex(proj.role)}} \\hfill \\small \\textbf{Tech Stack:} ${escapeLatex(proj.technologies.join(', '))}
\\begin{resumeItemize}
`;
      for (const bullet of proj.description) {
        latex += `  \\item ${escapeLatex(bullet)}\n`;
      }
      latex += `\\end{resumeItemize}
\\vspace{6pt}
`;
    }
    latex += `\\vspace{4pt}\n`;
  }

  // 4. Education Section
  if (data.education.length > 0) {
    latex += `%====================
% EDUCATION
%====================
\\section{Education}
`;

    for (const edu of data.education) {
      const dates = `${edu.startDate} -- ${edu.endDate}`;
      latex += `\\noindent
\\textbf{${escapeLatex(edu.institution)}} \\hfill \\small ${escapeLatex(edu.location)} \\\\
${escapeLatex(edu.degree)} in ${escapeLatex(edu.major)} ${edu.gpa ? `(GPA: ${escapeLatex(edu.gpa)})` : ''} \\hfill \\small \\textit{${escapeLatex(dates)}} \\\\
`;
      if (edu.details) {
        latex += `\\small \\textit{${escapeLatex(edu.details)}} \\\\ \n`;
      }
      latex += `\\vspace{6pt}\n`;
    }
    latex += `\\vspace{4pt}\n`;
  }

  // 5. Skills Section
  if (data.skills.length > 0) {
    latex += `%====================
% SKILLS
%====================
\\section{Technical Skills}
\\begin{tabular}{p{1.8in} p{4.2in}}
`;

    for (const skillCat of data.skills) {
      latex += `  \\textbf{${escapeLatex(skillCat.category)}:} & ${escapeLatex(skillCat.skills.join(', '))} \\\\\n`;
    }
    
    latex += `\\end{tabular}
\\vspace{10pt}
`;
  }

  // 6. Certifications
  if (data.certifications.length > 0) {
    latex += `%====================
% CERTIFICATIONS
%====================
\\section{Certifications}
\\begin{resumeItemize}
`;
    for (const cert of data.certifications) {
      latex += `  \\item \\textbf{${escapeLatex(cert.name)}} -- ${escapeLatex(cert.issuer)} (${escapeLatex(cert.date)})\n`;
    }
    latex += `\\end{resumeItemize}
\\vspace{6pt}
`;
  }

  // 7. Languages
  if (data.languages.length > 0) {
    latex += `%====================
% LANGUAGES
%====================
\\section{Languages}
\\begin{tabular}{p{1.8in} p{4.2in}}
`;
    for (const lang of data.languages) {
      latex += `  \\textbf{${escapeLatex(lang.name)}:} & ${escapeLatex(lang.proficiency)} \\\\\n`;
    }
    latex += `\\end{tabular}\n`;
  }

  latex += `\\end{document}
`;

  return latex;
}
